### ISSUE TITLE
仓库的config.plist中AppleCpuPmCfgLock为False

### ISSUE THREAD

**Issue by yanlusu** [hexart/T480-OpenCore-Hackintosh#12]
如果没有disable CFG-Unlock的话，AppleCpuPmCfgLock和AppleXcpmCfgLock不是应该是True吗？
为啥这个仓库中的前一个是False，后一个是True呢？
而且感觉没有disable CFG-Unlock的时候也运行正常。
这和官方的描述中有些违背。
是打了哪个补丁起的作用吗？

**Comment by hexart** [comment]
<img width="800" alt="截屏2022-04-16 13 49 46" src="https://user-images.githubusercontent.com/5528016/163663490-15f32048-c23b-4f66-9644-5a753bf191af.png">
coffeelake 只需要打第二个
