### ISSUE TITLE
SİDECAR

### ISSUE THREAD

**Issue by bugraduz** [hexart/T480-OpenCore-Hackintosh#2]
I can't use sidecar with my İPad 9th gen
it gives error : Sidecar not connecting, device timed out

**Comment by hexart** [comment]
What wireless card do you use? Which version of macOS do you use?

**Comment by bugraduz** [comment]
I have DW1820A BCM94352ZAE

macOS 12.0.1 Monterey

Macbook 15.2

**Comment by hexart** [comment]
Yes, I've confirmed this issue. Let's wait for BT driver becomes more stable.
