### ISSUE TITLE
请问一下你是通过什么方法解锁cfglock的

### ISSUE THREAD

**Issue by WonWaylon** [hexart/T480-OpenCore-Hackintosh#6]

**Comment by hexart** [comment]
没有解锁，所以这个config文件里的AppleXcpmCfgLock被设置为true

**Comment by WonWaylon** [comment]
这方法可以解锁，我已经试过了https://bbs.pcbeta.com/viewthread-1868855-1-1.html

**Comment by hexart** [comment]
是的，https://github.com/digmorepaka/thinkpad-firmware-patches 上也有小黑各个版本的补丁，但需要一定的动手能力和相应的工具。
