### ISSUE TITLE
T480-启动时有时候会卡住

### ISSUE THREAD

**Issue by yanlusu** [hexart/T480-OpenCore-Hackintosh#8]
你好：
启动的时候有时候会卡在：AppleKeyStore：863:0: oy vey
能麻烦帮忙看看大概是什么地方的问题吗？
谢谢
![IMG_3401](https://user-images.githubusercontent.com/1924699/160961308-aa7828f6-8487-498d-a0b4-6ecea945f614.jpg)

这是config.plist文件
[config.plist.txt](https://github.com/hexart/T480-OpenCore-Hackintosh/files/8385335/config.plist.txt)

**Comment by hexart** [comment]
检查一下BIOS设置

**Comment by yanlusu** [comment]
bios 配置都是按照README里设置的，重新设置过好几次了

**Comment by hexart** [comment]
![image](https://user-images.githubusercontent.com/5528016/161433852-fb35656c-13a8-4dff-ac2c-52077dc25492.png)

**Comment by yanlusu** [comment]
我把NVMeFix.kext删掉后，就不再出现启动卡住的情况了，谢谢回复。
